CREATE TABLE IF NOT EXISTS sys_user
(
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    progress INT NULL DEFAULT NULL COMMENT '年龄'
);

CREATE TABLE IF NOT EXISTS TASK
(
    id BIGINT PRIMARY KEY NOT NULL,
    progress INT NOT NULL
)
