CREATE TABLE IF NOT EXISTS sys_user
(
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱'
);

CREATE TABLE IF NOT EXISTS TASK
(
    id BIGINT PRIMARY KEY NOT NULL,
    progress INT NOT NULL
)
