CREATE TABLE IF NOT EXISTS sys_user
(
    id BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    progress INT NULL DEFAULT NULL COMMENT '年龄'
);

CREATE TABLE IF NOT EXISTS TASK
(
    id BIGINT PRIMARY KEY NOT NULL,
    progress INT NOT NULL
);

CREATE TABLE IF NOT EXISTS person
(
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    PRO1 VARCHAR(50) NULL DEFAULT NULL,
    PRO2 VARCHAR(50) NULL DEFAULT NULL,
    PRO3 VARCHAR(50) NULL DEFAULT NULL,
    PRO4 VARCHAR(50) NULL DEFAULT NULL,
    PRO5 VARCHAR(50) NULL DEFAULT NULL,
    PRO6 VARCHAR(50) NULL DEFAULT NULL,
    PRO7 VARCHAR(50) NULL DEFAULT NULL,
    PRO8 VARCHAR(50) NULL DEFAULT NULL,
    PRO9 VARCHAR(50) NULL DEFAULT NULL,
    PRO10 VARCHAR(50) NULL DEFAULT NULL,
    PRO11 VARCHAR(50) NULL DEFAULT NULL,
    PRO12 VARCHAR(50) NULL DEFAULT NULL,
    PRO13 VARCHAR(50) NULL DEFAULT NULL,
    PRO14 VARCHAR(50) NULL DEFAULT NULL
);